FROM silkeh/clang:11-bullseye

RUN apt update && apt install -y \
    git \
    cmake \
    clang-format \
    clang-tools \
    python3 \
    python3-pip \
    valgrind \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
    
RUN pip3 install cpplint